### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 573** [tweag/jupyenv#465]
### Current Behavior

jupyenv when started fails with

>OSError: [Errno 99] Cannot assign requested address

### Expected Behavior

Address getting assigned and logged

### Steps To Reproduce

1. flakes enabled
2. In an new folder: `nix flake init --template github:tweag/jupyterWith`
3. `nix run`

### OS

```shell
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.79.1-microsoft-standard-WSL2, NixOS, 22.11 (Raccoon), 22.11.20230307.a7cc819`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/bmyw96kdilalipziklp47rva12f0fhbz-source`
```

### Version

"rev":⋅"3ad2c9512c9efd586cf63adde454e734a8ce049c"

### Relevant log output

```shell
>[I 2023-03-20 11:11:50.907 ServerApp] nbclassic | extension was successfully loaded.
Traceback (most recent call last):
  File "/nix/store/kzndcs6zwrsih1mnyf8x11hgh5yfy9c5-python3.10-jupyterlab-3.6.1/bin/.jupyter-lab-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 607, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 577, in initialize_server
    serverapp.initialize(
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2548, in initialize
    self.init_httpserver()
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2371, in init_httpserver
    self._find_http_port()
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2418, in _find_http_port
    sockets = bind_sockets(port, self.ip)
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by 573** [comment]
WORKAROUND: `nix run .#apps.x86_64-linux.default -- --ip=0.0.0.0`
