### ISSUE TITLE
[Bug]: `Got '0o677' instead of '0o0600'` permission error when running using Quick Start instructions

### ISSUE THREAD

**Issue by Q-Mart** [tweag/jupyenv#473]
### Current Behavior

RuntimeError: Permissions assignment failed for secure file: '.jupyter/runtime/jpserver-18476.json'. Got '0o677' instead of '0o0600'.

### Expected Behavior

The notebook server runs without this error

### Steps To Reproduce

Follow steps in the quick start instructions on the [Getting Started](https://jupyenv.io/documentation/getting-started/) page. When running `nix run`, the error occurs.

### OS

```shell
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.11 (Raccoon), 22.11.3667.87edbd74246`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(q): `"nixos-22.11"`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Version

"rev": "3ad2c9512c9efd586cf63adde454e734a8ce049c"

### Relevant log output

```shell
$ nix run
warning: Git tree '/my/path/jupyenv' is dirty
warning: Using saved setting for 'extra-substituters = https://tweag-jupyter.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = tweag-jupyter.cachix.org-1:UtNH4Zs6hVUFpFBTLaA4ejYavPo5EFFqgd7G7FxGW9g=' from ~/.local/share/nix/trusted-settings.json.
warning: ignoring untrusted substituter 'https://tweag-jupyter.cachix.org'
[2023-04-13 11:06:12 jupyenv] does not need build JupyterLab.
[2023-04-13 11:06:12 jupyenv] Starting...
[I 2023-04-13 11:06:13.112 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-04-13 11:06:13.116 ServerApp] Package jupyter_server_fileid took 0.0029s to import
[I 2023-04-13 11:06:13.122 ServerApp] Package jupyter_server_terminals took 0.0056s to import
[I 2023-04-13 11:06:13.153 ServerApp] Package jupyter_server_ydoc took 0.0310s to import
[I 2023-04-13 11:06:13.154 ServerApp] Package nbclassic took 0.0000s to import
[W 2023-04-13 11:06:13.156 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-04-13 11:06:13.156 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-04-13 11:06:13.156 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-04-13 11:06:13.164 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-04-13 11:06:13.170 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-04-13 11:06:13.177 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-04-13 11:06:13.186 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-04-13 11:06:13.190 NotebookApp] 'use_redirect_file' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-04-13 11:06:13.199 ServerApp] nbclassic | extension was successfully linked.
/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
[I 2023-04-13 11:06:13.479 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-04-13 11:06:13.726 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-04-13 11:06:13.727 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-04-13 11:06:13.727 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /files/Programs/gen_art/autoencoder
[I 2023-04-13 11:06:13.727 FileIdExtension] ArbitraryFileIdManager : Configured database path: .jupyter/data/file_id_manager.db
[I 2023-04-13 11:06:13.728 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-04-13 11:06:13.728 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-04-13 11:06:13.729 FileIdExtension] Attached event listeners.
[I 2023-04-13 11:06:13.729 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-04-13 11:06:13.730 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-04-13 11:06:13.731 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-04-13 11:06:13.732 LabApp] JupyterLab extension loaded from /nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab
[I 2023-04-13 11:06:13.732 LabApp] JupyterLab application directory is /files/Programs/gen_art/autoencoder/.jupyter/lab/share/jupyter/lab
[I 2023-04-13 11:06:13.735 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-04-13 11:06:13.739 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-04-13 11:06:13.740 ServerApp] Serving notebooks from local directory: /files/Programs/gen_art/autoencoder
[I 2023-04-13 11:06:13.740 ServerApp] Jupyter Server 2.4.0 is running at:
[I 2023-04-13 11:06:13.740 ServerApp] http://localhost:8888/lab?token=2614559cee47a38d78555bbc741e47ca3588d41c4396bae5
[I 2023-04-13 11:06:13.740 ServerApp]     http://127.0.0.1:8888/lab?token=2614559cee47a38d78555bbc741e47ca3588d41c4396bae5
[I 2023-04-13 11:06:13.740 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/nix/store/kzndcs6zwrsih1mnyf8x11hgh5yfy9c5-python3.10-jupyterlab-3.6.1/bin/.jupyter-lab-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 617, in launch_instance
    serverapp.start()
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2897, in start
    self.start_app()
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2809, in start_app
    self.write_server_info_file()
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2616, in write_server_info_file
    with secure_write(self.info_file) as f:
  File "/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyter_core/paths.py", line 999, in secure_write
    raise RuntimeError(msg)
RuntimeError: Permissions assignment failed for secure file: '.jupyter/runtime/jpserver-20828.json'. Got '0o677' instead of '0o0600'.
```

**Comment by GTrunSec** [comment]
closes by #524
