### ISSUE TITLE
[Bug]: Build Failed - weback: command not found

### ISSUE THREAD

**Issue by grenewode** [tweag/jupyenv#538]
### Current Behavior

When attempting to start the application with `nix run`, the application attempts to build itself, but fails with the following error:

```
$ webpack --config webpack.prod.minimize.config.js
/bin/sh: line 1: webpack: command not found
```

### Expected Behavior

The application should start up normally, without issues.

### Steps To Reproduce

1. Pull the template into an empty directory
2. `nix run`

### OS

```shell
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 23.11 (Tapir), 23.11.20240410.b2cf36f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/bwibdavbf6p8lci025h3qmln6laq5x82-source`
```

### Version

main

### Relevant log output

```shell
[LabBuildApp] Building in /[redacted]/.jupyter/lab/share/jupyter/lab
[LabBuildApp] Node v18.13.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.22s.

[LabBuildApp] > node /nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /[redacted]/.jupyter/lab/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.24s.

[LabBuildApp] > node /nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
/bin/sh: line 1: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/labapp.py", line 204, in start
    raise e

[LabBuildApp]   File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/labapp.py", line 195, in start
    build(

[LabBuildApp]   File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/commands.py", line 506, in build
    return handler.build(

[LabBuildApp]   File "/nix/store/i2ihlpzkbcysdyq8srhh3xlpmv6cskgy-python3-3.10.9-env/lib/python3.10/site-packages/jupyterlab/commands.py", line 722, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by GTrunSec** [comment]
closes by #524
